"""New Migration

Revision ID: 49479e62d0f3
Revises: 
Create Date: 2023-03-20 12:33:04.727476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49479e62d0f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pole',
    sa.Column('pole_id', sa.Integer(), nullable=False),
    sa.Column('linear_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('pole_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('pole_id')
    )
    op.create_index(op.f('ix_pole_pole_id'), 'pole', ['pole_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pole_pole_id'), table_name='pole')
    op.drop_table('pole')
    # ### end Alembic commands ###
